/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'berinle' at '3/28/16 10:45 AM' with Gradle 2.11
 *
 * @author berinle, @date 3/28/16 10:45 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
