import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'berinle' at '3/28/16 10:44 AM' with Gradle 2.11
 *
 * @author berinle, @date 3/28/16 10:44 AM
 */
public class ModuleBLibraryTest {
    @Test public void testSomeLibraryMethod() {
        ModuleBLibrary classUnderTest = new ModuleBLibrary();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
